{% set version = "0.7.1" %}

package:
  name: nose-timer
  version: {{ version }}

source:
  fn: nose-timer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/nose-timer/nose-timer-{{ version }}.tar.gz
  sha256: 843ec3bd46cb7864aa79eaa3084d897055252d856c19010ddb9ddbcd6bbbf064
  patches:
    ############################################################
    # Drop unneeded ordereddict dependency.                    #
    #                                                          #
    # xref: https://github.com/mahmoudimus/nose-timer/pull/84  #
    ############################################################
    - PR_84.diff

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - nose
    - termcolor

test:
  imports:
    - nosetimer

  commands:
    - nosetests --with-timer

about:
  home: https://github.com/mahmoudimus/nose-timer
  license: MIT
  license_file: LICENSE
  summary: A timer plugin for nosetests.

extra:
  recipe-maintainers:
    - jakirkham
