{% set version = "0.7.5" %}

package:
  name: nose-timer
  version: {{ version }}

source:
  fn: nose-timer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/nose-timer/nose-timer-{{ version }}.tar.gz
  sha256: 647eeac86359188ecf02c75b0ab49d20ad10c41814ee89af30fcaf8d109b9f17

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - nose
    - termcolor

test:
  imports:
    - nosetimer

  commands:
    - nosetests --with-timer

about:
  home: https://github.com/mahmoudimus/nose-timer
  license: MIT
  license_file: LICENSE
  summary: A timer plugin for nosetests.

extra:
  recipe-maintainers:
    - jakirkham
