{% set name = "nose-timer" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f70d103b7ffd9122a589de0df9d037a7d967519bf6de122621d2186609b9e3a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - nose
    - python >={{ python_min }}
    - termcolor

test:
  imports:
    - nosetimer
  commands:
    - nosetests --with-timer
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mahmoudimus/nose-timer
  summary: A timer plugin for nosetests
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jakirkham
    - BastianZim
