{% set version = "0.7.6" %}

package:
  name: nose-timer
  version: {{ version }}

source:
  fn: nose-timer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/nose-timer/nose-timer-{{ version }}.tar.gz
  sha256: d8a2b49df0caf364d406c417cbe1608805428b1620cfb19942726546f6e510ab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - nose
    - termcolor

test:
  imports:
    - nosetimer

  commands:
    - nosetests --with-timer

about:
  home: https://github.com/mahmoudimus/nose-timer
  license: MIT
  license_file: LICENSE
  summary: A timer plugin for nosetests.

extra:
  recipe-maintainers:
    - jakirkham
